config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, :only => [:create]
  end
    root to: 'pages#home'
    get  'about', to: 'pages#about'
    get  'blog', to: 'pages#blog'
    get 'local', to: 'pages#local'
    get 'global', to: 'pages#global'
    resources :contacts, only: [:create]
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :body, :title
    
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
        def create
                @post = Post.find(params[:post_id])
                @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
                redirect_to @post
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      
       flash[:success] = "Message sent."
      redirect_to new_contact_path

    else 
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  private def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
    def about
        
    end
    def blog
        
    end
    def local
        
    end
    def global
        
    end
    
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [ :index, :show ]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end
 private
  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "admin" && password == "secret"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Us</h3>
    <div class="col-md-4 col-md-offset-4">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-default'%>
        <% end %>

      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenMark</title>
    <link rel="http://fontawesome.io/icon/envira/"/>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Antic+Slab|Noto+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Skranji:700" rel="stylesheet"> 
  </head>

<body>

  
  
  

  <nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      <i href="images/icon.ico"></i>
      <img src="images/icon.ico" style="height:50px; margin-top:0px;"></img>
      GreenMark
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right"> 
                <li>
          <%= link_to "Blog", blog_path %>
        </li>
          <li>
            <div class="dropdown" >
            <button class="btn btn-default dropdown-toggle" id="dropdown" type="button"  data-toggle="dropdown" style="" >
              GreenNews &nbsp;&nbsp;
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "Local", local_path %></li>
              <li class="last"><%= link_to "Global", global_path %></li>
          </ul>
        </li>
        
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li style="border-right: none;">          <%= link_to "Contact Us", new_contact_path %>
        </li>

      </ul>
    </div><!-- /.navbar-collapse  -->
  </div>
</nav>

  <%= yield %>
  
  
  <script src="https://twitter.com/javascripts/blogger.js" type="text/javascript"></script>
  <script src="https://twitter.com/statuses/user_timeline/YourEcolution.json?callback=twitterCallback2&count=1" type="text/javascript"></script>
  </body>


</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About GreenMark</h1>
    <p>Howdy and Welcome. GreenMark - The Ecolution is an online platform focused on nature and environment. With passion and a critical eye, we publish post, articles and other content on today's and everyday green topic bearing in mind that environmental solutions are usually hard to find and easy to attack. Even so, solutions are needed, both on large as well as small scale. We do have the data, now we need the action. What's your Green Mark on the world? Let's think, talk and act for the environment to find efficient and practical environmental solutions and continue the environmental revolution.</p>
</div>

app/views/pages/blog.html.erb
  
      <div class="other">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>


<%= link_to 'New Post', new_post_path %>
    </div>    
    <div class="blog"> 
        <div class="top">
            <h1>Latest Post</h1>
        </div>
        <h1 class="title">Less Is More — Reducing Consumerism To Save Nature</h1>
        <p= class="metadata">Author: Mark Miller, <%= Time.now %></p>
        
        <p class="text">Recently, I got rid of approximately 15 bags of clothes, books, games, house items, old documents and school notes. I did not just throw them away: I either brought them to secondhand markets and thrift shops or gave them to friends and charity organizations like Caritas or brought them, eventually, to recycling centers. I could not believe how difficult it was to find people willing to reuse those objects. Especially since a lot of them were still in very good condition. Looking for new owners was a time-consuming operation but I really felt better afterwards: I knew that those items were not just waste and could be still useful to someone. </p>
        <p class="text">To be honest, in the process of tiding up I was inspired by the instructions of this terrific book.</p>
        <img class="blogimage" src="images/Blogpost1/picture1.png"> 
        <img class="blogimage" src="images/Blogpost1/picture3.png"> 
    
        
        <p class="text">This masterpiece has strongly altered consolidated habits of my life. Yes, I really mean it. I used to be one of those people that has troubles in throwing away stuff. I would rather store it. Now, I am different. Marie Kondo used the right words to convince me that my attitude was wrong: Archiving thousands of stuffs and struggling to find the right place where to keep them, is just a way to postpone the act of deleting. In our daily life, we should apply two important buttons as we do with our email accounts: archive and delete. However, the delete button should be used more often as we should conserve only “what makes our heart beat”.</p>
        <p class="text">Understanding that we can live much happier without many objects around us is crucial to liberate ourselves from superfluous objects and, instead, start fighting against consumerism. This belief will help us do more rational shopping, rather than allowing marketing to persuade us. To do so, we should bear in mind the following questions when shopping: “Do I really need that? Will I really love that item? How often will I use it? Will it make me truly happy?”</p>
        <p class="text">What is happiness? Unfortunately, recent studies have shown that happiness is a state of joy, which is nowadays not only related to what we own, but also what we own compared to others. Meanwhile we try to change our selfish human psyche, we should adopt a temporary quick solution: Let us think that the less belongings we have around, the more freedom we have. It may sound paradoxical for some, but it will grant us more freedom than to those that stick to consumerism.</p>
        <p class="text">Marie Kondo was not the only person that pushed me towards minimalism. As a backpacker, I understand the importance of traveling light. This realization became even more intense three weeks ago, when I travelled to Cologne (Germany) together with four pieces of luggage. Insane. Anyhow, here is the second character: Ryan Bingham.</p>
        
        <p class="text">Now I do not 100% agree with the reflections of Ryan Bingham (alias George Clooney) on the meaning of life, but his explanation of life using the backpack similitude is great. What is really important in our life? Are we giving enough attention, time, money, energy, effort to those things that really matter to us? Or are we more disturbed by all the thousands of irrelevant things that surround us? Maybe we should start filtering that noise.</p>
        <p class="text">The motto “Less is more” was spread throughout the world thanks to the famous German-American architect Ludwig Mies van der Rohe. In this sense, art can help us elaborate on the beauty of having less belongings but of higher value. This implies having only few objects but of excellent value, minimalist items but efficiently designed, tidy rooms instead of unusable spaces, cleaned-up email accounts instead of chaotic and spam-full screens, ordered lives and focused minds. With this interior order, we can manage daily stresses, inputs, disordered activities and emergencies much better. One could argue that this way of living comes from a brutal engineer’s thought process and it constrains life to a matter of duties, to-do lists and categorizations. This, however, is not true. Giving that our life is a journey and the sense of the journey is the journey itself (excursus), we consciously or unconsciously know that we also want to reach some goals during our journey. These goals can be better achieved with a free mind and an organized plan: here is exactly when Mrs. Kondo can come in handy.</p>
        <p class="text">Ryan Bingham’s “live-in-the-moment” philosophy is not just a way to avoid stress and forget all worries (hakuna matata). It is about thinking that our thoughts, feelings, words and actions of the past, regardless their relevance and intensity they had, are less important that the ones of today. This is totally coherent with the advises of Mrs. Kondo and that is what really helped me get rid of a lot stuff. We must honor our memories, our habits and our great achievements of the past but we must remember that they are only important because they are the things that made us become what we are now. What we live in the present is far more important of what we lived yesterday. There is only one verse in this life and therefore we must follow it.</p>


        <figure style="text-align: center;">
            <img class="blogimage" src="images/Blogpost1/picture2.png"> 
            <figcaption>Delete and archive stuff to help nature as nature acts in the same way: Panta Rei, everything changes.</figcaption>
        </figure>
        <p class="text">PS: Another great man talked about minimalism.</p>
        <p class="text">(Luke 18:22)<br>
        “All these I have kept since I was a boy,” he said. <br>
        When Jesus heard this, he said to him, “You still lack one thing. Sell everything you have and give to the poor, and you will have treasure in heaven. Then come, follow me.”</p>
            
    </div>
    
    <div class="other">
            <h1>Blogentry 213</h1>
    </div>    

app/views/pages/home.html.erb
<div class="background">
	<div class="home-callout text-center container-fluid">
		<i src =""></i>
	</div>
	<div class="about">
		<div class="aboutinfo">
			<h1 style="font-family: 'Skranji', cursive;">Welcome to GreenMark!</h1>
		</div>
		<div class="blogbutton">
		<br>
		<a href="https://ruby-practice2-littleluk.c9users.io/blog">
	    <button type="button" class="btn btn" id="mainbutton">
	              <%= link_to "Proceed to Blog", blog_path %>
	    </button>
	    </a>
		</div>
		<div class="socialmedia">
			<h3>Follow us on Social Media!</h3>
			<a href="https://twitter.com/YourEcolution"><i class="fa fa-twitter-square" style="font-size: 2.5em;" aria-hidden="true"></i></a>
			&nbsp; &nbsp; &nbsp; &nbsp;
			<i class="fa fa-telegram" style="font-size: 2.5em;" aria-hidden="true"></i>
			&nbsp; &nbsp;
			<a href="https://medium.com/@MarkLawMiller"><i class="fa fa-medium" style="font-size: 2.5em;" aria-hidden="true"></i></a>
			&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
			<a href="https://open.spotify.com/user/markisthinkingabout"><i class="fa fa-spotify" style="font-size: 2.5em;" aria-hidden="true"></i></a>
		</div>
		<div class="contact">
			<br>
			<button type="button" class="btn btn" id="contactus" >
			
	              <%= link_to "Contact us", about_path %>
	    </button>
			
		</div>
	</div>
	
<div class="footer">
  <div class="bottom">
    <h4>GreenMark &#169 2017</h4>
    <p> This webpage was made by GreenMark</p>
    <p> Responsible for this page are:</p>
    <p> Mark Miller and Lukas Stellwag</p>
  </div>
</div>
</div>
  

	
<!-- <div class="container home">
		<div class="container" style="padding-top: 0px; height: 80%" >
		  <br>
		  <div id="myCarousel" class="carousel slide" data-ride="carousel" >
		    <!-- Indicators 
		    <ol class="carousel-indicators">
		      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		      <li data-target="#myCarousel" data-slide-to="1"></li>
		      <li data-target="#myCarousel" data-slide-to="2"></li>
		      <li data-target="#myCarousel" data-slide-to="3"></li>
		    </ol>

		    <!-- Wrapper for slides 
		    <a href="index.html">
			    <div class="carousel-inner" role="listbox" >

			      <div class="item active">
			        <img src="images/sea.jpg" alt="Sea" width="500" height="300" align="middle">
			        <div class="carousel-caption">
			          <h3>Baltic Sea</h3>
			          <p>Unpolluted air - Between Holmsund (Sweden) and Vaasa (Finland)</p>
			        </div>
			      </div>

			      <div class="item">
			        <img src="images/skuleskogen.png" alt="skuleskogen" width="500" height="300" align="middle">
			        <div class="carousel-caption">
			          <h3>Skuleskogen National Park</h3>
			          <p>Silence - Skuleskogen Natural Park, Västernorrland County (Sweden)</p>
			        </div>
			      </div>
			    
			      <div class="item">
			        <img src="images/aurora.jpg" alt="aurora" width="500" height="300" align="middle">
			        <div class="carousel-caption">
			          <h3>Aurora Borealis</h3>
			          <p>Darkness - Nydala Lake, Umeå (Sweden)</p>
			        </div>
			      </div>
			  	 <div class="item">
			        <img src="images/reindeer.png" alt="Flower" width="500" height="300" align="middle">
			        <div class="carousel-caption">
			          <h3>Reindeers</h3>
			          <p>A reindeer in Swedish Lappland</p>
			        </div>
			      </div>
			    </div>
		    </a>

		    <!-- Left and right controls 
		    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		      <span class="sr-only">Previous</span>
		    </a>
		    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		      <span class="sr-only">Next</span>
		    </a>
		  </div>
		</div>
    </div>
    
    -->
    

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
 <h2><%= link_to_unless_current @post.title, @post %></h2>
 <%= simple_format @post.body %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 <p id="notice"><%= notice %></p>

<%= render :partial => @post %>

 <%= link_to 'Edit', edit_post_path(@post) %> |
 <%= link_to 'Back', posts_path %>
 
 <%= form_for [@post, Comment.new] do |f| %>
        <p>
                <%= f.label :body, "New comment" %><br/>
                <%= f.text_area :body %>
        </p>
        <p><%= f.submit "Add comment" %></p>
<% end %>